environment:
  global:
    PROJECT_NAME: rust-clippy
    RUST_BACKTRACE: 1
  matrix:
    - TARGET: x86_64-pc-windows-msvc

branches:
  only:
    - dummy_dummy_dummy

build_script:
  - echo "Dummy"

notifications:
  - provider: Email
    on_build_success: false
